version: 1
root:
    level: DEBUG
    handlers: [console, file]
formatters:
    simpleFormater:
        format: "%(asctime)s\t%(levelname)s\t%(threadName)s\t%(message)s"
#            datefmt: '%Y-%m-%d %H:%M:%S.%f'

handlers:
    console:
        class: logging.StreamHandler
        formatter: simpleFormater
        level: DEBUG
        stream: ext://sys.stdout
    file:
        class : logging.FileHandler
        formatter: simpleFormater
        level: DEBUG
        filename: rabbit.log

loggers:
    pika:
        propagate: false
        level: DEBUG
        handlers: [console]
    occo:
        propagate: false
        level: DEBUG
        handlers: [console]
    clogger:
        level: DEBUG
        handlers: [console]
    flogger:
        level: WARNING
        handlers: [file]
